import { FiArrowUpRight } from "react-icons/fi"
import { InviteNowCard } from "./InviteNowCard"
import { SummaryInvitations } from "./SummaryInvitations"

export const RefIntroduction = () => {
    return (
        <section className="xl:py-24 pt-18 pb-6">
            <div className="site-width-sm">
                <h2 className="h2-tag md:text-4xl font-bold text-white max-w-[900px] mx-auto text-center">Refer & Earn – Turn Your Network into On-Chain Income</h2>
                <p className="p-tag mt-4 text-center">Grow the ABCDEX community while unlocking lifetime earning potential. Share your unique referral link, help your friends trade smarter with discounted fees, and earn real commissions every time they make a trade.  </p>
                <div className="text-center w-[245px] mx-auto mt-8">
                    <button className="text-xl flex items-center gap-1 border border-[#37373C] px-4 py-3 rounded-2xl justify-center">View referral rules <FiArrowUpRight className="text-xl" /></button>
                </div>

                <div className="grid md:grid-cols-2 grid-cols-1 gap-4 mt-20 max-w-6xl mx-auto">
                    <InviteNowCard />
                    <SummaryInvitations />
                </div>
                <RefHistory />
                <ReferralPage />
            </div>
        </section>
    )
}


import { Users, Gift } from "lucide-react";
import { RefHistory } from "./RefHistory"

function ReferralPage() {
    return (
        <section className="bg-[#0d0d11] text-white xl:pt-32 pt-18">
            <div className="site-width-sm mx-auto">

                {/* Heading */}
                <h1 className="h2-tag font-bold text-center">
                    How It Works
                </h1>
                <p className="text-center p-tag text-gray-300 mt-3">
                    Simple. Transparent. Automatic.
                </p>

                {/* Steps */}
                <div className="mt-12 space-y-10 grid md:grid-cols-3 gap-5 grid-cols-1">
                    <StepCard
                        title="Generate a unique referral link"
                        text="Connect your wallet and instantly receive your personalized referral URL."
                    />
                    <StepCard
                        title="Share it with your community"
                        text="Post it on social media or share it directly with traders."
                    />
                    <StepCard
                        title="Whenever they trade, you earn"
                        text="Every swap, every perp trade, or transaction will generate rewards for you."
                    />
                </div>

                {/* Rewards Section */}
                <h2 className="h3-tag font-bold mt-20">
                    The Rewards Structure
                </h2>
                <p className="p-tag text-gray-300 mt-2">
                    We designed our referral program to reward community builders fairly and transparently.
                </p>

                <div className="grid md:grid-cols-2 grid-cols-1 gap-8 mt-10">
                    {/* Referrer */}
                    <div className="bg-white/5 p-8 rounded-2xl border border-white/10">
                        <h3 className="text-2xl font-bold flex items-center gap-2">
                            <Users /> For You (The Referrer)
                        </h3>

                        <ul className="mt-4 space-y-3 text-lg">
                            <li>
                                <span className="font-bold text-white">20% Lifetime Commission:</span>{" "}
                                Earn 20% of trading fees generated by all users you invite — forever.
                            </li>
                            <li>
                                <span className="font-bold text-white">Instant Payouts:</span>{" "}
                                Rewards are paid immediately in stablecoins (USDC) via smart contract.
                            </li>
                            <li>
                                <span className="font-bold text-white">Points Boost (Optional):</span>{" "}
                                If tied into the Airdrop system, earn bonus Airdrop Points proportional to your referees’ trading volume.
                            </li>
                        </ul>
                    </div>

                    {/* Referee */}
                    <div className=" bg-white/5 p-8 rounded-2xl border border-white/10">
                        <h3 className="text-2xl font-bold flex items-center gap-2">
                            <Gift /> For Your Friends (The Referee)
                        </h3>

                        <ul className="mt-4 space-y-3 text-lg">
                            <li>
                                <span className="font-bold text-white">10% Fee Discount:</span>{" "}
                                They receive a permanent 10% discount on taker fees for joining with your link.
                            </li>
                            <li className="text-white/90">
                                It’s a true win-win: cheaper trades for them, lifetime income for you.
                            </li>
                        </ul>
                    </div>
                </div>
                {/* Terms */}
                <h2 className="h3-tag font-bold mt-20">Terms & Conditions</h2>

                <ul className="mt-6 space-y-4 text-lg text-gray-300">
                    <li>
                        <span className="font-bold text-white">No Self-Referrals:</span>{" "}
                        Creating multiple wallets or referring yourself is strictly prohibited.
                        Sybil-detection systems will identify related wallets, and violators risk losing
                        referral privileges and eligibility for future airdrops.
                    </li>

                    <li>
                        <span className="font-bold text-white">No Spam:</span>{" "}
                        Do not post referral links in official ABCDEX community channels.
                    </li>

                    <li>
                        <span className="font-bold text-white">Protocol Governance May Adjust Rates:</span>{" "}
                        Commission percentages and fee discounts may evolve based on governance proposals or market conditions.
                    </li>
                </ul>
            </div>
        </section>
    );
}

/* Reusable Components */

const StepCard = ({ title, text }: { title: string, text: string }) => (
    <div className="bg-white/5 p-6 rounded-2xl shadow-md border border-white/10">
        <h3 className="text-2xl font-semibold mb-2">{title}</h3>
        <p className="text-gray-300 text-lg">{text}</p>
    </div>
);

